package com.ruoyi.flow.form.service.impl;

import com.ruoyi.flow.form.vo.DefaultFieldInfoVO;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Service;

@Service
@Scope("prototype")
public class BuildFlowMybatisInterfaceService extends BuildMybatisInterfaceService {
    public   BuildFlowMybatisInterfaceService(){
        this.buildType=3;
        DefaultFieldInfoVO defaultFieldInfoVO=new DefaultFieldInfoVO();
        defaultFieldInfoVO.setFieldName("fid");
        defaultFieldInfoVO.setFieldType(" varchar(20) NOT NULL ");
        defaultFieldInfoVO.setIsPublic(true);
        defaultFieldInfoVO.setDescribe("主键");
        defaultFieldInfoVO.setIsPrimaryKey(true);
        defaultFieldInfoVO.setFieldAssignment("#{$tableNewId}");
        defaultFieldlist.add(defaultFieldInfoVO);
        DefaultFieldInfoVO defaultFieldInfoVO2=new DefaultFieldInfoVO();
        defaultFieldInfoVO2.setFieldName("fcreationdate");
        defaultFieldInfoVO2.setFieldType("  datetime(0) DEFAULT NULL ");
        defaultFieldInfoVO2.setIsPublic(true);
        defaultFieldInfoVO2.setIsGridShow(true);
        defaultFieldInfoVO2.setDescribe("创建时间");
        defaultFieldInfoVO2.setFieldAssignment("now()");
        defaultFieldInfoVO2.setWhereSql("<if test=\"fcreationdate!=null and fcreationdate.size()>0\">and maintable.fcreationdate between #{fcreationdate[0]} and #{fcreationdate[1]}  </if>");
        defaultFieldlist.add(defaultFieldInfoVO2);
        DefaultFieldInfoVO defaultFieldInfoVO3=new DefaultFieldInfoVO();
        defaultFieldInfoVO3.setFieldName("fcreateby");
        defaultFieldInfoVO3.setFieldType(" varchar(20)   DEFAULT NULL ");
        defaultFieldInfoVO3.setIsPublic(true);
        defaultFieldInfoVO3.setDescribe("创建人");
        defaultFieldInfoVO3.setFieldAssignment("#{$user.userCode}");
        defaultFieldlist.add(defaultFieldInfoVO3);
        DefaultFieldInfoVO defaultFieldInfoVO4=new DefaultFieldInfoVO();
        defaultFieldInfoVO4.setFieldName("fcreatebyname");
        defaultFieldInfoVO4.setFieldType(" varchar(50)   DEFAULT NULL ");
        defaultFieldInfoVO4.setIsPublic(true);
        defaultFieldInfoVO4.setDescribe("创建人");
        defaultFieldInfoVO4.setIsGridShow(true);
        defaultFieldInfoVO4.setFieldAssignment("#{$user.userName}");
        defaultFieldInfoVO4.setWhereSql("<if test=\"fcreatebyname!=null and fcreatebyname!=''\">and maintable.fcreatebyname  like CONCAT('%',#{fcreatebyname},'%')  </if>");
        defaultFieldlist.add(defaultFieldInfoVO4);
        DefaultFieldInfoVO defaultFieldInfoVO5=new DefaultFieldInfoVO();
        defaultFieldInfoVO5.setFieldName("flastupdatedate");
        defaultFieldInfoVO5.setFieldType(" datetime(0) DEFAULT NULL ");
        defaultFieldInfoVO5.setIsPublic(true);
        defaultFieldInfoVO5.setDescribe("最后修改时间");
        defaultFieldInfoVO5.setIsUpdate(true);
        defaultFieldInfoVO5.setIsGridShow(true);
        defaultFieldInfoVO5.setFieldAssignment("now()");
        defaultFieldlist.add(defaultFieldInfoVO5);
        DefaultFieldInfoVO defaultFieldInfoVO6=new DefaultFieldInfoVO();
        defaultFieldInfoVO6.setFieldName("flastupdateby");
        defaultFieldInfoVO6.setFieldType(" varchar(20)   DEFAULT NULL ");
        defaultFieldInfoVO6.setIsPublic(true);
        defaultFieldInfoVO6.setIsUpdate(true);
        defaultFieldInfoVO6.setDescribe("最后修改人");
        defaultFieldInfoVO6.setFieldAssignment("#{$user.userCode}");
        defaultFieldlist.add(defaultFieldInfoVO6);
        DefaultFieldInfoVO defaultFieldInfoVO7=new DefaultFieldInfoVO();
        defaultFieldInfoVO7.setFieldName("flastupdatebyname");
        defaultFieldInfoVO7.setFieldType(" varchar(50)   DEFAULT NULL");
        defaultFieldInfoVO7.setIsPublic(true);
        defaultFieldInfoVO7.setIsUpdate(true);
        defaultFieldInfoVO7.setIsGridShow(true);
        defaultFieldInfoVO7.setFieldAssignment("#{$user.userName}");
        defaultFieldInfoVO7.setDescribe("最后修改人");
        defaultFieldlist.add(defaultFieldInfoVO7);
        DefaultFieldInfoVO defaultFieldInfoVO8=new DefaultFieldInfoVO();
        defaultFieldInfoVO8.setFieldName("procinsid");
        defaultFieldInfoVO8.setFieldType(" varchar(20) NOT NULL ");
        defaultFieldInfoVO8.setIsPublic(true);
        defaultFieldInfoVO8.setIsUpdate(true);
        defaultFieldInfoVO8.setDescribe("流程实例Id");
        defaultFieldInfoVO8.setFieldAssignment("#{procinsid}");
        defaultFieldlist.add(defaultFieldInfoVO8);
        DefaultFieldInfoVO defaultFieldInfoVO9=new DefaultFieldInfoVO();
        defaultFieldInfoVO9.setFieldName("actinsid");
        defaultFieldInfoVO9.setFieldType(" varchar(20) DEFAULT NULL ");
        defaultFieldInfoVO9.setIsPublic(true);
        defaultFieldInfoVO9.setIsUpdate(true);
        defaultFieldInfoVO9.setDescribe("节点实例");
        defaultFieldInfoVO9.setFieldAssignment("#{actinsid}");
        defaultFieldlist.add(defaultFieldInfoVO9);
        DefaultFieldInfoVO defaultFieldInfoVO10=new DefaultFieldInfoVO();
        defaultFieldInfoVO10.setFieldName("procinsname");
        defaultFieldInfoVO10.setFieldType(" varchar(200) DEFAULT NULL ");
        defaultFieldInfoVO10.setIsPublic(true);
        defaultFieldInfoVO10.setIsUpdate(true);
        defaultFieldInfoVO10.setIsGridShow(true);
        defaultFieldInfoVO10.setDescribe("流程名称");
        defaultFieldInfoVO10.setFieldAssignment("#{procinsname}");
        defaultFieldInfoVO10.setWhereSql("<if test=\"procinsname!=null and procinsname!=''\">and maintable.procinsname  like CONCAT('%',#{procinsname},'%')  </if>");
        defaultFieldlist.add(defaultFieldInfoVO10);
        DefaultFieldInfoVO defaultFieldInfoVO11=new DefaultFieldInfoVO();
        defaultFieldInfoVO11.setFieldName("procinsno");
        defaultFieldInfoVO11.setFieldType(" varchar(50) DEFAULT NULL ");
        defaultFieldInfoVO11.setIsPublic(true);
        defaultFieldInfoVO11.setIsUpdate(true);
        defaultFieldInfoVO11.setIsGridShow(true);
        defaultFieldInfoVO11.setDescribe("流程编号");
        defaultFieldInfoVO11.setFieldAssignment("#{procinsno}");
        defaultFieldInfoVO10.setWhereSql("<if test=\"procinsno!=null and procinsno!=''\">and maintable.procinsno  like CONCAT('%',#{procinsno},'%')  </if>");
        defaultFieldlist.add(defaultFieldInfoVO11);
        DefaultFieldInfoVO defaultFieldInfoVO12=new DefaultFieldInfoVO();
        defaultFieldInfoVO12.setFieldName("organcode");
        defaultFieldInfoVO12.setFieldType(" varchar(200)   DEFAULT NULL");
        defaultFieldInfoVO12.setIsPublic(true);
        defaultFieldInfoVO12.setIsUpdate(false);
        defaultFieldInfoVO12.setFieldAssignment("#{$user.officeCode}");
        defaultFieldInfoVO12.setDescribe("组织编码");
        defaultFieldlist.add(defaultFieldInfoVO12);

    }
}
